from enum import StrEnum

from pydantic import BaseModel, Field


class MealType(StrEnum):
    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"
    SNACK = "snack"


class RecipeSource(StrEnum):
    DRIVE = "drive"
    WEB = "web"
    MANUAL = "manual"


class NutritionConfidence(StrEnum):
    EXACT = "exact"
    ESTIMATED = "estimated"


class NutritionInfo(BaseModel):
    calories: int = Field(ge=0, le=5000, description="Calories per serving")
    protein_g: float = Field(ge=0, description="Protein in grams")
    carbs_g: float = Field(ge=0, description="Carbohydrates in grams")
    fat_g: float = Field(ge=0, description="Fat in grams")
    fiber_g: float = Field(ge=0, description="Fiber in grams")
    sodium_mg: float = Field(default=0, ge=0, description="Sodium in mg")
    sugar_g: float = Field(default=0, ge=0, description="Sugar in grams")
    cholesterol_mg: float = Field(default=0, ge=0, description="Cholesterol in mg")
    confidence: NutritionConfidence = NutritionConfidence.ESTIMATED
    source: str = Field(default="llm", description="e.g. usda, llm, manual")


class Ingredient(BaseModel):
    name: str = Field(min_length=1, description="Ingredient name")
    quantity: float = Field(gt=0, description="Amount needed")
    unit: str = Field(min_length=1, description="Unit of measurement (cups, g, tbsp, etc.)")
    substitutions: list[str] = Field(default_factory=list)


class RecipeRef(BaseModel):
    source: RecipeSource = RecipeSource.MANUAL
    url: str | None = None
    notes: str | None = None


class MealFlags(BaseModel):
    allergen_warnings: list[str] = Field(default_factory=list)
    rule_conflicts: list[str] = Field(default_factory=list)
    estimated_values: list[str] = Field(default_factory=list)


class Meal(BaseModel):
    meal_type: MealType
    title: str = Field(min_length=1, max_length=100)
    cook_time_min: int = Field(ge=0, le=480, description="Total cook time in minutes")
    servings: int = Field(ge=1, le=20)
    recipe: RecipeRef = Field(default_factory=RecipeRef)
    ingredients: list[Ingredient] = Field(min_length=1)
    nutrition: NutritionInfo
    flags: MealFlags = Field(default_factory=MealFlags)


class DayPlan(BaseModel):
    """Schema for a single day's meal plan. Generated by LLM one day at a time."""

    date: str = Field(description="ISO date string, e.g. 2026-02-16")
    meals: list[Meal] = Field(min_length=1)


class DailyTotal(BaseModel):
    date: str
    calories: int = Field(ge=0)
    protein_g: float = Field(ge=0)
    carbs_g: float = Field(ge=0)
    fat_g: float = Field(ge=0)
    fiber_g: float = Field(ge=0)


class ShoppingItem(BaseModel):
    name: str
    quantity: float
    unit: str
    category: str = Field(description="Produce, Meat, Dairy, Pantry, Spices, Other")


class ShoppingList(BaseModel):
    items: list[ShoppingItem] = Field(default_factory=list)


class ConstraintOverride(BaseModel):
    constraint_type: str
    description: str
    acknowledged_at: str


class WeeklyPlan(BaseModel):
    """Full weekly plan assembled server-side from DayPlan results."""

    week_start_date: str
    days: list[DayPlan] = Field(min_length=7, max_length=7)
    daily_totals: list[DailyTotal] = Field(default_factory=list)
    shopping_list: ShoppingList = Field(default_factory=ShoppingList)
    overrides: list[ConstraintOverride] = Field(default_factory=list)
