"""Initial schema

Revision ID: 068c0cc09a20
Revises: 
Create Date: 2026-02-21 12:11:01.267236

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '068c0cc09a20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('normalized_food', sa.String(length=255), nullable=False),
    sa.Column('nutrition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nutrition_cache_normalized_food', 'nutrition_cache', ['normalized_food'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_tokens_household_provider', 'oauth_tokens', ['household_id', 'provider'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('age_band', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_person_household_id', 'person', ['household_id'], unique=False)
    op.create_table('weekly_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PUBLISHED', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('model_info_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_plan_household_week', 'weekly_plan', ['household_id', 'week_start_date'], unique=False)
    op.create_table('allergy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='severity'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allergy_person_id', 'allergy', ['person_id'], unique=False)
    op.create_table('biometric',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dietary_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('rule', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('household_id IS NOT NULL OR person_id IS NOT NULL', name='ck_dietary_rule_scope'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dietary_rule_household_id', 'dietary_rule', ['household_id'], unique=False)
    op.create_index('ix_dietary_rule_person_id', 'dietary_rule', ['person_id'], unique=False)
    op.create_table('food_preference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('preference', sa.Enum('LIKE', 'DISLIKE', 'AVOID', 'FAVORITE', name='preference'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('household_id IS NOT NULL OR person_id IS NOT NULL', name='ck_food_preference_scope'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_preference_household_id', 'food_preference', ['household_id'], unique=False)
    op.create_index('ix_food_preference_person_id', 'food_preference', ['person_id'], unique=False)
    op.create_table('meal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('recipe_source_url', sa.Text(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('ingredients_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutrition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_goal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('calories_min', sa.Integer(), nullable=True),
    sa.Column('calories_max', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('household_id IS NOT NULL OR person_id IS NOT NULL', name='ck_nutrition_goal_scope'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_id', sa.UUID(), nullable=False),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exports_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list')
    op.drop_table('nutrition_goal')
    op.drop_table('meal')
    op.drop_index('ix_food_preference_person_id', table_name='food_preference')
    op.drop_index('ix_food_preference_household_id', table_name='food_preference')
    op.drop_table('food_preference')
    op.drop_index('ix_dietary_rule_person_id', table_name='dietary_rule')
    op.drop_index('ix_dietary_rule_household_id', table_name='dietary_rule')
    op.drop_table('dietary_rule')
    op.drop_table('biometric')
    op.drop_index('ix_allergy_person_id', table_name='allergy')
    op.drop_table('allergy')
    op.drop_index('ix_weekly_plan_household_week', table_name='weekly_plan')
    op.drop_table('weekly_plan')
    op.drop_index('ix_person_household_id', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_oauth_tokens_household_provider', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_table('memory_documents')
    op.drop_table('audit_log')
    op.drop_index('ix_nutrition_cache_normalized_food', table_name='nutrition_cache')
    op.drop_table('nutrition_cache')
    op.drop_table('household')
    # ### end Alembic commands ###
